In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv(r'/content/diabetes.csv')

In [4]:
df.shape

(768, 9)

In [5]:
df.dtypes

,0
Pregnancies,int64
Glucose,int64
BloodPressure,int64
SkinThickness,int64
Insulin,int64
BMI,float64
DiabetesPedigreeFunction,float64
Age,int64
Outcome,int64


In [6]:
y=df['Outcome']
y.ndim

1

In [7]:
x=df.drop('Outcome',axis=1)
x.ndim

2

In [8]:
from sklearn.model_selection import train_test_split
x_tr,x_te,y_tr,y_te=train_test_split(x,y,test_size=0.30)

In [9]:
x_tr.shape

(537, 8)

In [10]:
x_te.shape

(231, 8)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_tr)
x_tr=scaler.transform(x_tr)
x_te=scaler.transform(x_te)
x_tr

array([[-0.83366373, -0.28084157, -0.35104898, ..., -0.98422574,
        -1.04344308, -0.88210094],
       [-0.25414603,  0.15048977, -0.55011266, ..., -0.03697374,
        -1.00295576, -0.79841045],
       [-0.25414603,  1.62934009,  0.64426941, ...,  0.81056752,
         5.18226093, -0.71471995],
       ...,
       [-0.83366373,  0.9515337 , -0.45058082, ..., -0.72248506,
        -0.9157523 , -0.96579144],
       [-0.54390488,  0.24291792,  0.44520573, ...,  1.42129578,
         2.33880532, -0.21257698],
       [-0.25414603,  0.2737273 , -0.25151714, ..., -0.68509353,
        -0.79117593, -0.46364846]])

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=8)
knn.fit(x_tr,y_tr)
y_pred=knn.predict(x_te)


In [13]:
y_pred

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [14]:
y_te.values

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0])

In [15]:
print(knn.predict(scaler.transform([[6,148,72,35,0,33.6,0.627,50]])))

[1]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [16]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [17]:
def cscore(test,predd):
  print(accuracy_score(test,predd))
  print(confusion_matrix(test,predd))
  print(classification_report(test,predd))


In [18]:
cscore(y_te,y_pred)

0.7186147186147186
[[133  17]
 [ 48  33]]
              precision    recall  f1-score   support

           0       0.73      0.89      0.80       150
           1       0.66      0.41      0.50        81

    accuracy                           0.72       231
   macro avg       0.70      0.65      0.65       231
weighted avg       0.71      0.72      0.70       231

