In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv(r'/content/glass_knn_numeric.csv')

In [ ]:
df

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.5121,11.1,1.14,1.79,72.57,2.96,6.59,low,0.23,5
1,NaN,13.4,3.61,1.15,69.39,0.46,11.21,0.09,0.16,3
2,1.5129,NaN,3.55,3.42,71.72,1.25,10.55,2.4,0.02,6
3,1.5111,15.22,0.31,1.4,72.80,1.06,6.98,1.09,0.07,2
4,1.5117,11.58,3.02,2.7,73.90,3.61,14.47,1.74,0.26,2
...,...,...,...,...,...,...,...,...,...,...
115,1.5103,NaN,3.17,3.44,NaN,4.97,8.91,0.87,0.12,2
116,1.5105,15.6,2.72,0.4,71.23,0.76,12.71,1.41,0.13,5
117,NaN,11.22,1.0,3.2,73.98,5.38,15.32,NaN,0.34,7
118,1.5236,16.92,3.47,2.33,70.01,NaN,12.65,1.3,0.22,1


In [ ]:
df.isna().sum()

,0
RI,12
Na,12
Mg,12
Al,12
Si,12
K,12
Ca,12
Ba,12
Fe,12
Type,0


In [ ]:
x=df.columns
for i in x:
  print(i,df[i].unique())

RI [1.5121    nan 1.5129 1.5111 1.5117 1.5261 1.5184 1.5298 1.5286 1.5128
 1.5239 1.5237 1.5224 1.529  1.5299 1.5183 1.5233 1.5282 1.5207 1.519
 1.5281 1.5156 1.5234 1.5113 1.5275 1.525  1.5163 1.5215 1.5134 1.512
 1.5153 1.5242 1.5208 1.5279 1.5217 1.5101 1.5118 1.5123 1.5289 1.5126
 1.5238 1.5169 1.5258 1.517  1.5108 1.514  1.5147 1.5165 1.5179 1.5276
 1.5154 1.516  1.5212 1.5104 1.5285 1.5127 1.5182 1.5198 1.5277 1.5225
 1.5251 1.5245 1.5216 1.5218 1.5158 1.5205 1.5133 1.5292 1.5287 1.524
 1.5267 1.5142 1.5294 1.51   1.5171 1.5223 1.5293 1.518  1.5186 1.5125
 1.526  1.5103 1.5105 1.5236]
Na ['11.1' '13.4' nan '15.22' '11.58' '11.82' '15.41' '14.1' '11.68' '16.15'
 '16.04' '15.27' '16.79' '11.37' '16.43' '16.34' '10.14' '16.48' '12.41'
 '10.13' '16.77' '11.84' '14.34' '13.93' '11.63' '13.43' '10.1' '16.64'
 '14.32' '10.42' '10.15' '14.68' '13.22' '10.5' '12.66' '13.04' '11.95'
 '11.42' '10.75' '16.47' '13.92' '15.79' '13.77' '12.76' '13.67' '15.93'
 '15.21' '15.65' '11.35' '11.77' '1

In [ ]:
df['Na']=df['Na'].replace('fifteen',15)
df['Mg']=df['Mg'].replace('missing',np.nan)
df['Al']=df['Al'].replace('??',np.nan)
df['K']=df['K'].replace('none',np.nan)
df['Ba']=df['Ba'].replace('low',np.nan)
df['Fe']=df['Fe'].replace('zero',np.nan)


In [ ]:
for i in x:
  df[i]=df[i].astype(float)
  df[i]=df[i].fillna(df[i].mean())

In [ ]:
df.isna().sum()

,0
RI,0
Na,0
Mg,0
Al,0
Si,0
K,0
Ca,0
Ba,0
Fe,0
Type,0


In [ ]:
df['Al']

,Al
0,1.79
1,1.15
2,3.42
3,1.40
4,2.70
...,...
115,3.44
116,0.40
117,3.20
118,2.33


In [ ]:
x=df.drop('Type',axis=1)
x.ndim
y=df['Type']
y.ndim

1

In [ ]:
from sklearn.model_selection import train_test_split
x_tr,x_te,y_tr,y_te=train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_tr)
x_tr=sc.transform(x_tr)
x_te=sc.transform(x_te)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_tr,y_tr)
y_pred=knn.predict(x_te)

In [ ]:
y_pred

array([7., 1., 6., 1., 2., 2., 1., 1., 2., 6., 5., 3., 2., 6., 1., 2., 6.,
       6., 6., 1., 2., 6., 1., 5., 2., 2., 2., 6., 6., 2., 1., 1., 2., 5.,
       1., 5.])

In [ ]:
y_te.values

array([7., 3., 5., 5., 7., 2., 2., 6., 6., 5., 2., 2., 2., 1., 5., 2., 5.,
       1., 2., 3., 3., 5., 3., 5., 2., 3., 7., 7., 2., 1., 7., 6., 7., 3.,
       7., 6.])

In [ ]:
df

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.512100,11.100000,1.14,1.79,72.570000,2.960000,6.59,1.403738,0.23,5.0
1,1.520141,13.400000,3.61,1.15,69.390000,0.460000,11.21,0.090000,0.16,3.0
2,1.512900,13.441389,3.55,3.42,71.720000,1.250000,10.55,2.400000,0.02,6.0
3,1.511100,15.220000,0.31,1.40,72.800000,1.060000,6.98,1.090000,0.07,2.0
4,1.511700,11.580000,3.02,2.70,73.900000,3.610000,14.47,1.740000,0.26,2.0
...,...,...,...,...,...,...,...,...,...,...
115,1.510300,13.441389,3.17,3.44,71.959537,4.970000,8.91,0.870000,0.12,2.0
116,1.510500,15.600000,2.72,0.40,71.230000,0.760000,12.71,1.410000,0.13,5.0
117,1.520141,11.220000,1.00,3.20,73.980000,5.380000,15.32,1.403738,0.34,7.0
118,1.523600,16.920000,3.47,2.33,70.010000,2.908785,12.65,1.300000,0.22,1.0


In [ ]:
knn.predict(sc.transform([[1.511100,15.220000,0.31,1.40,72.800000,1.060000,6.98,1.090000,0.07]]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([2.])

In [ ]:
from sklearn.matrix